{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: {{ include "smokeping.fullname" . }}
spec:
  {{ tpl (toYaml .Values.prometheus.spec) . | nindent 2 }}
  serviceMonitorSelector:
    matchLabels:
      release: {{ include "smokeping.fullname" . }}
      componemt: smokeping-prober
  serviceAccountName: {{ include "smokeping.fullname" . }}-prometheus
{{end}}